apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-tester
  name: load-tester
  namespace: load-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-tester
  template:
    metadata:
      labels:
        app: load-tester
    spec:
      containers:
      - image: gcr.io/mercari-us-ml-dev/load-tester:latest
        name: load-tester
        command: ["sh", "-c", "tail -f /dev/null"]
        resources:
          limits:
            cpu: 4000m
            memory: 500Mi
          requests:
            cpu: 4000m
            memory: 500Mi