apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-service
  namespace: load-test
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: test-app