FROM python:3.7.7

RUN  mkdir -p /workspace
WORKDIR /workspace

COPY src ./src
COPY scripts ./scripts

COPY requirements/requirements_server.txt ./requirements.txt

RUN apt-get update && apt-get install -y libev-dev
RUN pip install -r requirements.txt
RUN pip install tensorflow==2.1.0
RUN pip install uWSGI==2.0.18

RUN mkdir ./data
RUN python -m src.dnn.tensorflow.save_model

ENV FRAMEWORK_TYPE tensorflow

ENTRYPOINT ["./scripts/run_server.sh"]