FROM pytorch/pytorch:latest

RUN  mkdir -p /workspace
WORKDIR /workspace

COPY src ./src
COPY scripts ./scripts

COPY requirements/requirements_server.txt ./requirements.txt

RUN apt-get update && apt-get install -y libev-dev
RUN pip install -r requirements.txt
RUN pip install onnxruntime

RUN mkdir ./data
RUN python -m src.dnn.onnxruntime.save_model

ENV FRAMEWORK_TYPE onnxruntime

ENTRYPOINT ["./scripts/run_server.sh"]