FROM pytorch/pytorch:latest

RUN  mkdir -p /workspace
WORKDIR /workspace

COPY src ./src
COPY scripts ./scripts

COPY requirements/requirements_server.txt ./requirements.txt

RUN apt-get update && apt-get install -y libev-dev
RUN pip install -r requirements.txt

RUN mkdir ./data

ENV FRAMEWORK_TYPE pytorch

ENTRYPOINT ["./scripts/run_server.sh"]