FROM continuumio/miniconda:4.7.12

RUN  mkdir -p /workspace
WORKDIR /workspace

COPY src ./src
COPY scripts ./scripts

COPY requirements/requirements_server.txt ./requirements.txt
COPY requirements/conda_environment.yml ./environment.yml

RUN apt-get update && apt-get install -y libev-dev
RUN conda env update -f environment.yml \
    && pip install -r requirements.txt \
    && conda clean -y --all

RUN mkdir ./data

ENV FRAMEWORK_TYPE pytorch

ENTRYPOINT ["./scripts/run_server.sh"]